# Generated by Django 5.0.7 on 2024-07-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_profile_selected_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
